# Generated by Django 5.0.6 on 2024-06-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(blank=True, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=10)),
                ('edad', models.PositiveBigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_exp', models.SmallIntegerField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_miembros.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_de_piel', models.CharField(max_length=30)),
                ('grado_escolar', models.CharField(max_length=15)),
                ('nuevo_ingreso', models.BooleanField(default=True)),
                ('continuante', models.BooleanField(default=True)),
                ('anno_exp_x_deporte', models.SmallIntegerField()),
                ('vive_con', models.CharField(blank=True, max_length=255, null=True)),
                ('padres_fallecidos', models.BooleanField(default=False)),
                ('ocupacion_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion_miembros.direccion')),
                ('grupo_etario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.grupoetario')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_miembros.persona')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion_miembros.municipio'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_miembros.pais')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_miembros.provincia'),
        ),
        migrations.CreateModel(
            name='RelacionEntrenadorGrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.entrenador')),
                ('grupo_etario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.grupoetario', to_field='rango_edad')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='grupo_etario',
            field=models.ManyToManyField(through='gestion_miembros.RelacionEntrenadorGrupoEtario', to='gestion_miembros.grupoetario'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_miembros.persona')),
                ('persona', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_persona', to='gestion_miembros.persona')),
            ],
            bases=('gestion_miembros.persona',),
        ),
    ]
