# Generated by Django 5.0.6 on 2024-06-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cualidades', '0001_initial'),
        ('gestion_miembros', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistVolSemContCualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='relaciongrupoetariocualidad',
            name='cualidad',
        ),
        migrations.RemoveField(
            model_name='distribucion',
            name='cualidad',
        ),
        migrations.RemoveField(
            model_name='relacioncualidadentrenador',
            name='cualidad',
        ),
        migrations.RemoveField(
            model_name='relaciondistribucioncualidades',
            name='cualidad',
        ),
        migrations.RemoveField(
            model_name='relaciondistribucioncualidades',
            name='distribucion',
        ),
        migrations.RemoveField(
            model_name='relacioncualidadentrenador',
            name='entrenador',
        ),
        migrations.RemoveField(
            model_name='relaciongrupoetariocualidad',
            name='grupo_etario',
        ),
        migrations.CreateModel(
            name='DistVolSemContCualFechaStd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False)),
                ('porciento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.fecha')),
                ('cualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cualidades.distvolsemcontcualidad')),
            ],
        ),
        migrations.CreateModel(
            name='DistVolSemNXContCualFechaEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False)),
                ('porciento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cualidades.distvolsemcontcualidad')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.entrenador')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.fecha')),
            ],
        ),
        migrations.DeleteModel(
            name='Cualidades',
        ),
        migrations.DeleteModel(
            name='Distribucion',
        ),
        migrations.DeleteModel(
            name='RelacionDistribucionCualidades',
        ),
        migrations.DeleteModel(
            name='RelacionCualidadEntrenador',
        ),
        migrations.DeleteModel(
            name='RelacionGrupoEtarioCualidad',
        ),
    ]
